# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GasTracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GasTracker
  pod 'RealmSwift'
  pod 'Backendless'
  pod 'FBSDKCoreKit', '~>4.15.1'
  pod 'FBSDKShareKit', '~>4.15.1'
  pod 'FBSDKLoginKit', '~>4.15.1'
  pod 'IQKeyboardManager'

end
